repos:
  - repo: local
    hooks:
      - id: ruff
        name: ruff
        entry: ruff check --force-exclude
        language: python
        types_or: [python, pyi]
        args: []
        require_serial: true

      - id: ruff-format
        name: ruff-format
        entry: ruff format --force-exclude
        language: python
        types_or: [python, pyi]
        args: []
        require_serial: true

